[package]
name = "grid-svm"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-bpf-loader-program = { workspace = true }
solana-compute-budget = { workspace = true }
solana-program-runtime = { workspace = true }
solana-system-program = { workspace = true }
