[package]
name = "grid-node"
description = ""
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[[bin]]
name = "grid"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
grid-core = { workspace = true }
grid-rpc = { workspace = true }
grid-storage = { workspace = true }
grid-svm = { workspace = true }
solana-rpc-client-api = { workspace = true }
tokio = { workspace = true }
